# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


title: Blake Lassiter
name: Blake Lassiter
baseurl: ''
markdown: kramdown

page_data:

  - title: "Home"
    id: "home"
    url: ""

  - title: "About"
    id: "about"
    url: "about"

  - title: "Blog"
    id: "blog"
    url: "blog"

  - title: "Readings"
    id: "readings"
    url: "readings"

  - title: "Resume"
    id: "resume"
    url: "resume"

  - title: "Training"
    id: "training"
    url: "training"
