title: Blake Lassiter Website
name: Blake Lassiter
baseurl: ""
markdown: kramdown

page_data:

  - title: "Home"
    id: "home"
    url: ""

  - title: "About"
    id: "contact"
    url: "about"

  - title: "Blog"
    id: "blog"
    url: "blog"

  - title: "Resume"
    id: "resume"
    url: "pdf/web/viewer.html?file=Resume.pdf"

  - title: "Training"
    id: "training"
    url: "training"

  - title: "Pace Chart"
    id: "pace-chart"
    url: "training/pace-chart"
